add task 03
mikhailolkhovskiy/made_2019_cpp pull request #3
Opened 2019-11-08 05:51 UTC by mikhailolkhovskiy

2019-11-10 15:15 UTC, smirnov-vs requested changes
привет!
надо правильно обработать ошибки

2019-11-10 15:15 UTC, smirnov-vs commented on 03/parser.cpp
> +            onString(buff);
строка скопирована в обработчик

2019-11-10 15:15 UTC, smirnov-vs commented on 03/test.cpp
> +    } catch (...) {
какие именно исключения ловятся?

2019-11-10 16:20 UTC, mikhailolkhovskiy commented on 03/test.cpp
> +    } catch (...) {
поправил

2019-11-10 16:27 UTC, mikhailolkhovskiy commented on 03/parser.cpp
> +            onString(buff);
правильно я понимаю что строка по значению в обработчик уйдет?

2019-11-12 20:30 UTC, smirnov-vs commented on 03/parser.cpp
> +            onString(buff);
ага

2019-11-12 20:31 UTC, smirnov-vs reviewed
можем либо закрыть задачу, либо исправлять до конца

2019-11-13 07:35 UTC, mikhailolkhovskiy commented on 03/parser.cpp
> +            onString(buff);
поправил сигнатуру колбека

2019-11-13 10:05 UTC, smirnov-vs approved these changes

2019-11-13 17:06 UTC, merged