task 4
mikhailolkhovskiy/made_2019_cpp pull request #4
Opened 2019-11-12 07:17 UTC by mikhailolkhovskiy

2019-11-12 20:43 UTC, smirnov-vs requested changes

2019-11-12 20:43 UTC, smirnov-vs commented on 04/matrix.cpp
> +    std::fill_n(data, size, 0);
скобки после new[] это zero initialization

2019-11-12 20:43 UTC, smirnov-vs commented on 04/matrix.cpp
> +void Matrix::operator*=(const int& v) {
такие операторы возвращают ссылку на себя

2019-11-12 20:43 UTC, smirnov-vs commented on 04/matrix.cpp
> +    return Matrix::AccessProxy((Matrix*)this, i);
конст касты запрещены

2019-11-12 20:43 UTC, smirnov-vs commented on 04/matrix.cpp
> +    if (row < 0 || row >= rows || column < 0 || column >= columns) {
меньше нуля не может быть

2019-11-12 20:43 UTC, smirnov-vs commented on 04/matrix.h
> +class OutOfRange: public std::exception {
такой класс есть в std

2019-11-13 08:15 UTC, mikhailolkhovskiy commented on 04/matrix.cpp
> +    std::fill_n(data, size, 0);
исправил

2019-11-13 08:16 UTC, mikhailolkhovskiy commented on 04/matrix.cpp
> +void Matrix::operator*=(const int& v) {
поправил

2019-11-13 08:16 UTC, mikhailolkhovskiy commented on 04/matrix.cpp
> +    return Matrix::AccessProxy((Matrix*)this, i);
сделал константную версию для AccessProxy
если честно то смотрится кривовато, как в С++ с этим обходятся?

2019-11-13 08:17 UTC, mikhailolkhovskiy commented on 04/matrix.cpp
> +    if (row < 0 || row >= rows || column < 0 || column >= columns) {
поправил

2019-11-13 08:17 UTC, mikhailolkhovskiy commented on 04/matrix.h
> +class OutOfRange: public std::exception {
заменил на стандартную

2019-11-18 20:14 UTC, smirnov-vs commented on 04/matrix.cpp
> +    return Matrix::AccessProxy((Matrix*)this, i);
в данном решении можно обойтись одним классом, если обходиться без указателей, тогда можно сделать 2 прокси класса через шаблоны

2019-11-18 20:14 UTC, smirnov-vs approved these changes
привет!
я зачел

2019-11-28 16:50 UTC, merged