add task 07
mikhailolkhovskiy/made_2019_cpp pull request #7
Opened 2019-12-01 09:34 UTC by mikhailolkhovskiy

2019-12-01 11:23 UTC, smirnov-vs requested changes

2019-12-01 11:23 UTC, smirnov-vs commented on 07/format.h
> +    Formatter(std::string tpl):tpl{tpl}{};
лишнее копирование

2019-12-01 11:23 UTC, smirnov-vs commented on 07/format.h
> +std::string format(std::string&& tpl, Args&&... args) {
что если формат строка lvalue?

2019-12-01 21:10 UTC, mikhailolkhovskiy commented on 07/format.h
> +    Formatter(std::string tpl):tpl{tpl}{};
исправил на & и &&

2019-12-01 21:10 UTC, mikhailolkhovskiy commented on 07/format.h
> +std::string format(std::string&& tpl, Args&&... args) {
добавил вариант с &

2019-12-11 19:55 UTC, smirnov-vs approved these changes
привет!
формально будет работать, но так никто не пишет, я задачу зачел

2019-12-11 19:55 UTC, smirnov-vs commented on 07/format.h
> +std::string format(std::string& tpl, Args&&... args) {
это плохой стиль, сразу видно что лекцию невнимательно изучал
`const std::string&`  достаточно

2019-12-16 22:53 UTC, merged