add task 08
mikhailolkhovskiy/made_2019_cpp pull request #8
Opened 2019-12-11 08:24 UTC by mikhailolkhovskiy

2019-12-11 22:01 UTC, smirnov-vs requested changes

2019-12-11 22:01 UTC, smirnov-vs commented on 08/vector.h
> +class Iterator: public std::iterator<std::bidirectional_iterator_tag, typename Container::value_type> {
не та категория

2019-12-11 22:01 UTC, smirnov-vs commented on 08/vector.h
> +class Iterator: public std::iterator<std::bidirectional_iterator_tag, typename Container::value_type> {
итератор не знает о контейнере, только о данных, на которые ссылается

2019-12-11 22:01 UTC, smirnov-vs commented on 08/vector.h
> +    std::fill(data, data + count, defaultValue);
слева мусор, так нельзя

2019-12-11 22:01 UTC, smirnov-vs commented on 08/vector.h
> +        data[i++] = *current++;
аналогично

2019-12-11 22:01 UTC, smirnov-vs commented on 08/vector.h
> +void Vector<T, Alloc>::push_back(value_type&& value) {
работает неправильно

2019-12-11 22:01 UTC, smirnov-vs commented on 08/vector.h
> +    if (!std::is_fundamental<value_type>::value) {
тут нужен if constexpr

2019-12-13 08:17 UTC, mikhailolkhovskiy commented on 08/vector.h
> +class Iterator: public std::iterator<std::bidirectional_iterator_tag, typename Container::value_type> {
исправил на указатель

2019-12-13 08:17 UTC, mikhailolkhovskiy commented on 08/vector.h
> +    std::fill(data, data + count, defaultValue);
поправил

2019-12-13 08:17 UTC, mikhailolkhovskiy commented on 08/vector.h
> +        data[i++] = *current++;
поправил

2019-12-13 08:17 UTC, mikhailolkhovskiy commented on 08/vector.h
> +void Vector<T, Alloc>::push_back(value_type&& value) {
добавил std::move

2019-12-13 08:18 UTC, mikhailolkhovskiy commented on 08/vector.h
> +    if (!std::is_fundamental<value_type>::value) {
добавил

2019-12-13 09:04 UTC, smirnov-vs approved these changes
теперь все окей

2019-12-16 22:53 UTC, merged